"""empty message

Revision ID: 29e1b1a9ad34
Revises: 86e7ffd25c69
Create Date: 2024-07-16 12:49:01.633597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e1b1a9ad34'
down_revision: Union[str, None] = '86e7ffd25c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_statuses_id'), 'task_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_task_statuses_title'), 'task_statuses', ['title'], unique=True)
    op.add_column('tasks', sa.Column('expected_completion_date', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('actual_completion_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('hours_spent', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('task_status_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_task_status_id', 'tasks', 'task_statuses', ['task_status_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_status_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_status_id')
    op.drop_column('tasks', 'hours_spent')
    op.drop_column('tasks', 'actual_completion_date')
    op.drop_column('tasks', 'expected_completion_date')
    op.drop_index(op.f('ix_task_statuses_title'), table_name='task_statuses')
    op.drop_index(op.f('ix_task_statuses_id'), table_name='task_statuses')
    op.drop_table('task_statuses')
    # ### end Alembic commands ###
