"""empty message

Revision ID: 878de1f0bfe5
Revises: a615714baa97
Create Date: 2024-07-12 10:51:36.512386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878de1f0bfe5'
down_revision: Union[str, None] = 'a615714baa97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_projects_title', table_name='projects')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=True)
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['project_id', 'title'])
    op.create_foreign_key('fk_project_id', 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_id', 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_index('ix_projects_title', 'projects', ['title'], unique=False)
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
