stages:
  - build
  - test
  - deploy



build:
  stage: build
  image: docker:latest

  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build
    - docker compose -f docker/test/docker-compose.yml up
    - echo "Всё хорошо 2"




test:
  stage: test
  script:
    - echo "Всё хорошо 3"




deploy:
  stage: deploy
  script:
    - echo "Всё хорошо 4"
