stages:
  - build
  - test
  - deploy

variables:
  IMAGE_BASE: $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME
  IMAGE: $IMAGE_BASE:latest

services:
  - name: docker:dind
    alias: dind


build:
  stage: build
  image: docker:latest
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    # - docker tag test-fastapi:latest $IMAGE
    - docker push $IMAGE



test:
  stage: test
  image: docker:latest
  script:
    - docker images
    - docker compose up -d
    - export CONTAINER_ID=$(docker compose ps -q web)
    - docker ps
    - until [ "`docker inspect -f  $CONTAINER_ID`"=="true" ]; do sleep 0.1; done;
    - docker exec --tty $CONTAINER_ID pytest tests/employees/employee.py
    - docker exec --tty $CONTAINER_ID pytest tests/employees/vacation.py
    - docker exec --tty $CONTAINER_ID pytest tests/employees/business_trip.py
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Всё хорошо 4"
