stages:
  - build
  - test
  - deploy

variables:
  IMAGE_BASE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  IMAGE: $IMAGE_BASE:latest


build:
  stage: build
  image: docker:latest
  script:
    # - docker compose -f docker/test/docker-compose.yml down
    # - docker compose -f docker/test/docker-compose.yml build
    - docker build -t $IMAGE_BASE ./docker/test/docker-compose.yml
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag test-fastapi:latest $IMAGE
    - docker images
    - docker push $IMAGE

test:
  stage: test
  image: python:3.10
  script:
    - docker compose -f docker/test/docker-compose.yml up -d
    - export CONTAINER_ID=$(docker compose ps -q web)
    - docker ps
    - until [ "`docker inspect -f  $CONTAINER_ID`"=="true" ]; do sleep 0.1; done;
    - docker exec --tty $CONTAINER_ID pytest tests/employees/employee.py
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "Всё хорошо 4"
