stages:
  - build
  - test
  - deploy


variables:
  DOCKER_IMAGE: registry.gitlab.com/saveleva/user-service:latest


build:
  stage: build
  image: docker:latest

  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "Всё хорошо"

  only:
    main


test:
  stage: test

  only:
    main



deploy:
  stage: deploy

  only:
    main
