stages:
  - build
  - test
  - deploy


variables:
  DOCKER_IMAGE: registry.gitlab.com/saveleva/user-service:latest


requirements:
  stage: build
  image: python:3.10
  script:
    - pip install -r fastapi/requirements/test.txt
    - - echo "Всё хорошо 1"



build:
  stage: build
  image: docker:latest

  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "Всё хорошо 2"




test:
  stage: test
  script:
    - echo "Всё хорошо 3"




deploy:
  stage: deploy
  script:
    - echo "Всё хорошо 4"
