stages:
  - build
  - test
  - deploy

variables:
  IMAGE_BASE: $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME
  IMAGE: $IMAGE_BASE:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker tag test-fastapi:latest $IMAGE
    - docker push $IMAGE

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker ps
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker pull $IMAGE
    - docker tag $IMAGE test-fastapi:latest
    - docker compose -f docker/test/docker-compose.yml up -d
    - docker ps
    - export CONTAINER_ID=$(docker compose ps -q userservice_fastapi)
    - docker ps
    - echo $CONTAINER_ID
    - docker exec --tty $CONTAINER_ID pytest
    # - docker exec --tty $CONTAINER_ID pytest #tests/employees/employee.py
    # - docker exec --tty $CONTAINER_ID pytest #tests/employees/vacation.py
    # - docker exec --tty $CONTAINER_ID pytest #tests/employees/business_trip.p
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo "deploy stage"
