stages:
  - build
  - test
  - deploy

variables:
  IMAGE_BASE: $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME
  IMAGE: $IMAGE_BASE:latest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f gitlab-docker-compose.yml down
    - docker compose -f gitlab-docker-compose.yml build
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker tag test-user_service:latest $IMAGE
    - docker push $IMAGE

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker pull $IMAGE
    - docker tag $IMAGE test-user_service:latest
    - docker compose -f gitlab-docker-compose.yml up -d
    - export CONTAINER_ID=$(docker ps --filter "name=userservice_fastapi" --format "{{.ID}}")
    - docker exec --tty $CONTAINER_ID pytest tests/employees/employee.py
    - docker exec --tty $CONTAINER_ID pytest tests/employees/vacation.py
    - docker exec --tty $CONTAINER_ID pytest tests/employees/business_trip.py

deploy:
  stage: deploy
  script:
    - echo "deploy stage"

