stages:
  - build
  - test
  - deploy


variables:
  DOCKER_IMAGE: registry.gitlab.com/saveleva/user-service:latest


build:
  stage: build
  image: docker:latest

  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "Всё хорошо"



test:
  stage: test
  script:
    - echo "Всё хорошо"




deploy:
  stage: deploy
  script:
    - echo "Всё хорошо"

