stages:
  - build
  - test
  - deploy



build:
  stage: build
  image: docker:latest

  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build
    - docker compose -f docker/test/docker-compose.yml up -d




test:
  stage: test
  image: python:3.10
  script:
    - pytest tests/employees/employee.py


deploy:
  stage: deploy
  script:
    - echo "Всё хорошо 4"
