"""empty message

Revision ID: 4027468a9fd3
Revises: 446d553c61f4
Create Date: 2024-06-14 21:38:29.073581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4027468a9fd3'
down_revision: Union[str, None] = '446d553c61f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
