"""empty message

Revision ID: 4ce4b7c5ff40
Revises: 4b0eab401aa2
Create Date: 2024-06-14 19:22:54.846552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce4b7c5ff40'
down_revision: Union[str, None] = '4b0eab401aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employee_unit_id', 'employees', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    op.add_column('units', sa.Column('director_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_unit_director_id', 'units', 'employees', ['director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unit_director_id', 'units', type_='foreignkey')
    op.drop_column('units', 'director_id')
    op.drop_constraint('fk_employee_unit_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'unit_id')
    # ### end Alembic commands ###
