"""empty message

Revision ID: 6b7f21933be5
Revises: f8c962d22820
Create Date: 2024-06-14 17:00:33.768481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7f21933be5'
down_revision: Union[str, None] = 'f8c962d22820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['employees.id'], name='fk_unit_director_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('employees', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_employee_unit_id', 'employees', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employee_unit_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'unit_id')
    op.drop_table('units')
    # ### end Alembic commands ###
