"""empty message

Revision ID: 7df796615a57
Revises: 87778f6c939b
Create Date: 2024-05-18 17:12:49.946365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df796615a57'
down_revision: Union[str, None] = '87778f6c939b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('vacations', sa.Column('vacation_reason_id', sa.Integer(), nullable=False))
    op.add_column('vacations', sa.Column('comment', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vacations', 'vacation_reasons', ['vacation_reason_id'], ['id'])
    op.drop_column('vacations', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacations', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vacations', type_='foreignkey')
    op.drop_column('vacations', 'comment')
    op.drop_column('vacations', 'vacation_reason_id')
    op.drop_table('vacation_reasons')
    # ### end Alembic commands ###
