"""empty message

Revision ID: c93891c7663e
Revises: 0d021be0ddaf
Create Date: 2024-05-29 11:09:09.083142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93891c7663e'
down_revision: Union[str, None] = '0d021be0ddaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_trips', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_trips', 'comment')
    # ### end Alembic commands ###
