"""empty message

Revision ID: cd6f2c6289d8
Revises: e149a76c65ff
Create Date: 2024-05-17 19:56:53.677447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6f2c6289d8'
down_revision: Union[str, None] = 'e149a76c65ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'units', ['unit_id'], ['id'])
    op.add_column('units', sa.Column('director_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'units', 'employees', ['director_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_column('units', 'director_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'unit_id')
    # ### end Alembic commands ###
