"""empty message

Revision ID: e6d0b50cbf5d
Revises: cd6f2c6289d8
Create Date: 2024-05-18 11:30:54.950209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d0b50cbf5d'
down_revision: Union[str, None] = 'cd6f2c6289d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
